### ISSUE TITLE
noob trying to get this working

### ISSUE THREAD

**Issue by gerardwknight** [haloboy777/keyboard-driver#1]
Hi, I new to Linux and not much of a c coder. I have a problem with a POS system where I need to inject keystrokes pretending to be a USB keyboard, its a long story, but the POS has written its own keyboard handler and will only accept keystrokes from an actual USB keyboard ie they cannot be injected vi xwindows.

I was hoping to use your code as a basis. I followed your instructions
sudo make
sudo insmod usbkbd.ko

and the message log indicates that usbkbd was registerd. At this point I was expecting that any key a pressed on the existing USB keyboard would be logged because of this line
...
printk(KERN_ALERT "key pressed is %d",usb_kbd_keycode[i+224]);
...

but nothing is logged. Have I missunderstood how this works. There are also two other modules that can be compiled driver.c and haloboy777-key.c, are they relevant or just test code?

Any help would be appreciated.

Gerry

**Comment by haloboy777** [comment]
So sorry for the delay

**Comment by shrynshjn** [comment]
Did you detach the keyboard using libhid-detach-device command?
I had the same issue.
This is how i solved it.
if you inserted the module (insmod) before doing so
First use,
 sudo rmmod usbkbd.ko 
to remove the loaded module
then detach the usb keyboard
and again insert the module
Use
   dmesg -wH 
to see the output in real time as each is pressed.

**Comment by haloboy777** [comment]
Yeah pretty much what he said.
